### ISSUE TITLE
Error fetching stuff

### ISSUE THREAD

**Issue by Galebourn** [shish/cview3#2]
Hello,
I'm not sure if this software is still supported in any way, since it's been at least 4 years, but I can't find a good alternative for it.
Anyway, I set everything up as I should, but I only get the "Error feching stuff" message. It's installed in a subfolder of the webspace, if that makes any difference.
The structure (cview/books/bookname/01/page001.jpg) is exactly as it should.
Any clue why it doesn't work?

**Comment by shish** [comment]
It's not actively developed since it does everything that I personally need, but I'm still willing to help where I can :)

In this case, is the site public at all so I can look myself? If not, can you check the browser network console (in chrome, ctrl-shift-i -> click the network tab) and see if it is fetching data correctly? I would expect either 404 (if the folder name isn't as expected). 403 (if permissions aren't set to allow listing of directories) or 500 (if there's some other server config error)

**Comment by Galebourn** [comment]
Wow, I didn't expect such a fast answer.

I used the console like you said and it turned out to be a problem with the permissions. I thought it had access to everything, but adding a htaccess file to the folder did the trick.
Thanks for everything.
